parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: c9
    database_user: mac8905
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: 61ce3d2d9c1a2667a320d65717285bf6371c9514
    database_driver: pdo_mysql
    database_path: null
